name: flutter_pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.20.2
  switcher: 1.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.3
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  provider: ^6.1.5+1
  dio: ^5.9.0
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
